coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "app/src/main/kotlin/**/MainActivity.kt"
  - "app/src/main/kotlin/**/SettingsActivity.kt"
  - "app/src/main/kotlin/**/AppAdapter.kt"
  - "app/src/main/kotlin/**/GridAutofitLayoutManager.kt"
  - "app/src/main/kotlin/**/AppExporter.kt"
  - "app/src/main/kotlin/**/AndroidStorageService.kt"
  - "app/src/main/kotlin/**/AndroidUsageStatsService.kt"
  - "app/src/test/**"
  - "app/src/androidTest/**"

comment:
  behavior: default
  require_changes: false
